language: node_js
node_js:
  - "node"
before_deploy:
- yarn build
deploy:
  - provider: npm
    skip-cleanup: true
    email: "danny.wieser@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
